language: bash

sudo: required

before_install:
    - sudo apt-get install ncurses-dev
    - cd /tmp
    - wget http://jaist.dl.sourceforge.net/sourceforge/zsh/zsh-5.0.7.tar.gz
    - tar zxvf zsh-5.0.7.tar.gz
    - cd zsh-5.0.7
    - ./configure && make && sudo make install

before_script:
    - zsh --version
    - curl -fLo ~/.zplug/zplug --create-dirs git.io/zplug
      
script:
    - zsh -c 'source ~/.zplug/zplug; zplug b4b4r07/http_code, as:command, of:bin; zplug install; zplug load; which http_code'
